module AreaService
  def self.seed_areas
    # Create Areas
    ankara = Area.create!(name: 'Ankara', type: 'land', supply_center: true, power: 'turkey')
    belgium = Area.create!(name: 'Belgium', type: 'land', supply_center: true)
    berlin = Area.create!(name: 'Berlin', type: 'land', supply_center: true, power: 'germany')
    brest = Area.create!(name: 'Brest', type: 'land', supply_center: true, power: 'france')
    budapest = Area.create!(name: 'Budapest', type: 'land', supply_center: true, power: 'austria')
    bulgaria = Area.create!(name: 'Bulgaria', type: 'land', supply_center: true)
    constantinople = Area.create!(name: 'Constantinople', type: 'land', supply_center: true, power: 'turkey')
    denmark = Area.create!(name: 'Denmark', type: 'land', supply_center: true)
    edinburgh = Area.create!(name: 'Edinburgh', type: 'land', supply_center: true, power: 'england')
    greece = Area.create!(name: 'Greece', type: 'land', supply_center: true)
    holland = Area.create!(name: 'Holland', type: 'land', supply_center: true)
    kiel = Area.create!(name: 'Kiel', type: 'land', supply_center: true, power: 'germany')
    liverpool = Area.create!(name: 'Liverpool', type: 'land', supply_center: true, power: 'england')
    london = Area.create!(name: 'London', type: 'land', supply_center: true, power: 'england')
    marseilles = Area.create!(name: 'Marseilles', type: 'land', supply_center: true, power: 'france')
    moscow = Area.create!(name: 'Moscow', type: 'land', supply_center: true, power: 'russia')
    munich = Area.create!(name: 'Munich', type: 'land', supply_center: true, power: 'germany')
    naples = Area.create!(name: 'Naples', type: 'land', supply_center: true, power: 'italy')
    norway = Area.create!(name: 'Norway', type: 'land', supply_center: true)
    paris = Area.create!(name: 'Paris', type: 'land', supply_center: true, power: 'france')
    portugal = Area.create!(name: 'Portugal', type: 'land', supply_center: true)
    rome = Area.create!(name: 'Rome', type: 'land', supply_center: true, power: 'italy')
    rumania = Area.create!(name: 'Rumania', type: 'land', supply_center: true)
    saint_petersburg = Area.create!(name: 'Saint Petersburg', type: 'land', supply_center: true, power: 'russia')
    serbia = Area.create!(name: 'Serbia', type: 'land', supply_center: true)
    sevastopol = Area.create!(name: 'Sevastopol', type: 'land', supply_center: true, power: 'russia')
    smyrna = Area.create!(name: 'Smyrna', type: 'land', supply_center: true, power: 'turkey')
    spain = Area.create!(name: 'Spain', type: 'land', supply_center: true)
    sweden = Area.create!(name: 'Sweden', type: 'land', supply_center: true)
    trieste = Area.create!(name: 'Trieste', type: 'land', supply_center: true, power: 'austria')
    tunis = Area.create!(name: 'Tunis', type: 'land', supply_center: true)
    venice = Area.create!(name: 'Venice', type: 'land', supply_center: true, power: 'italy')
    vienna = Area.create!(name: 'Vienna', type: 'land', supply_center: true, power: 'austria')
    warsaw = Area.create!(name: 'Warsaw', type: 'land', supply_center: true, power: 'russia')
    clyde = Area.create!(name: 'Clyde', type: 'land', supply_center: false)
    yorkshire = Area.create!(name: 'Yorkshire', type: 'land', supply_center: false)
    wales = Area.create!(name: 'Wales', type: 'land', supply_center: false)
    picardy = Area.create!(name: 'Picardy', type: 'land', supply_center: false)
    gascony = Area.create!(name: 'Gascony', type: 'land', supply_center: false)
    burgundy = Area.create!(name: 'Burgundy', type: 'land', supply_center: false)
    north_africa = Area.create!(name: 'North Africa', type: 'land', supply_center: false)
    ruhr = Area.create!(name: 'Ruhr', type: 'land', supply_center: false)
    prussia = Area.create!(name: 'Prussia', type: 'land', supply_center: false)
    silesia = Area.create!(name: 'Silesia', type: 'land', supply_center: false)
    piedmont = Area.create!(name: 'Piedmont', type: 'land', supply_center: false)
    tuscany = Area.create!(name: 'Tuscany', type: 'land', supply_center: false)
    apulia = Area.create!(name: 'Apulia', type: 'land', supply_center: false)
    tyrolia = Area.create!(name: 'Tyrolia', type: 'land', supply_center: false)
    galicia = Area.create!(name: 'Galicia', type: 'land', supply_center: false)
    bohemia = Area.create!(name: 'Bohemia', type: 'land', supply_center: false)
    finland = Area.create!(name: 'Finland', type: 'land', supply_center: false)
    livonia = Area.create!(name: 'Livonia', type: 'land', supply_center: false)
    ukraine = Area.create!(name: 'Ukraine', type: 'land', supply_center: false)
    albania = Area.create!(name: 'Albania', type: 'land', supply_center: false)
    armenia = Area.create!(name: 'Armenia', type: 'land', supply_center: false)
    syria = Area.create!(name: 'Syria', type: 'land', supply_center: false)
    north_atlantic_ocean = Area.create!(name: 'North Atlantic Ocean', type: 'sea', supply_center: false)
    mid_atlantic_ocean = Area.create!(name: 'Mid Atlantic Ocean', type: 'sea', supply_center: false)
    norwegian_sea = Area.create!(name: 'Norwegian Sea', type: 'sea', supply_center: false)
    north_sea = Area.create!(name: 'North Sea', type: 'sea', supply_center: false)
    english_channel = Area.create!(name: 'English Channel', type: 'sea', supply_center: false)
    irish_sea = Area.create!(name: 'Irish Sea', type: 'sea', supply_center: false)
    heligoland_bight = Area.create!(name: 'Heligoland Bight', type: 'sea', supply_center: false)
    skagerrack = Area.create!(name: 'Skagerrack', type: 'sea', supply_center: false)
    baltic_sea = Area.create!(name: 'Baltic Sea', type: 'sea', supply_center: false)
    gulf_of_bothnia = Area.create!(name: 'Gulf of Bothnia', type: 'sea', supply_center: false)
    barents_sea = Area.create!(name: 'Barents Sea', type: 'sea', supply_center: false)
    western_mediterranean = Area.create!(name: 'Western Mediterranean', type: 'sea', supply_center: false)
    gulf_of_lyons = Area.create!(name: 'Gulf of Lyons', type: 'sea', supply_center: false)
    tyrrhenian_sea = Area.create!(name: 'Tyrrhenian Sea', type: 'sea', supply_center: false)
    ionian_sea = Area.create!(name: 'Ionian Sea', type: 'sea', supply_center: false)
    adriatic_sea = Area.create!(name: 'Adriatic Sea', type: 'sea', supply_center: false)
    aegean_sea = Area.create!(name: 'Aegean Sea', type: 'sea', supply_center: false)
    eastern_mediterranean = Area.create!(name: 'Eastern Mediterranean', type: 'sea', supply_center: false)
    black_sea = Area.create!(name: 'Black Sea', type: 'sea', supply_center: false)

    # Create coasts
    saint_petersburg_nc = Coast.create!(area: saint_petersburg, direction: 'north')
    saint_petersburg_sc = Coast.create!(area: saint_petersburg, direction: 'south')
    spain_nc = Coast.create!(area: spain, direction: 'north')
    spain_sc = Coast.create!(area: spain, direction: 'south')
    bulgaria_sc = Coast.create!(area: bulgaria, direction: 'south')
    bulgaria_ec = Coast.create!(area: bulgaria, direction: 'east')

    # Create neighbor mappings
    Neighbor.create!(area: ankara, neighbor: black_sea)
    Neighbor.create!(area: ankara, neighbor: armenia)
    Neighbor.create!(area: ankara, neighbor: smyrna)
    Neighbor.create!(area: ankara, neighbor: constantinople)

    Neighbor.create!(area: belgium, neighbor: english_channel)
    Neighbor.create!(area: belgium, neighbor: north_sea)
    Neighbor.create!(area: belgium, neighbor: holland)
    Neighbor.create!(area: belgium, neighbor: ruhr)
    Neighbor.create!(area: belgium, neighbor: burgundy)
    Neighbor.create!(area: belgium, neighbor: picardy)

    Neighbor.create!(area: berlin, neighbor: baltic_sea)
    Neighbor.create!(area: berlin, neighbor: prussia)
    Neighbor.create!(area: berlin, neighbor: silesia)
    Neighbor.create!(area: berlin, neighbor: munich)
    Neighbor.create!(area: berlin, neighbor: kiel)

    Neighbor.create!(area: brest, neighbor: english_channel)
    Neighbor.create!(area: brest, neighbor: mid_atlantic_ocean)
    Neighbor.create!(area: brest, neighbor: picardy)
    Neighbor.create!(area: brest, neighbor: paris)
    Neighbor.create!(area: brest, neighbor: gascony)

    Neighbor.create!(area: budapest, neighbor: galicia)
    Neighbor.create!(area: budapest, neighbor: rumania)
    Neighbor.create!(area: budapest, neighbor: serbia)
    Neighbor.create!(area: budapest, neighbor: trieste)
    Neighbor.create!(area: budapest, neighbor: vienna)

    Neighbor.create!(area: bulgaria, neighbor: rumania)
    Neighbor.create!(area: bulgaria, neighbor: black_sea)
    Neighbor.create!(area: bulgaria, neighbor: constantinople)
    Neighbor.create!(area: bulgaria, neighbor: aegean_sea)
    Neighbor.create!(area: bulgaria, neighbor: greece)
    Neighbor.create!(area: bulgaria, neighbor: serbia)

    Neighbor.create!(area: constantinople, neighbor: bulgaria_sc)
    Neighbor.create!(area: constantinople, neighbor: bulgaria)
    Neighbor.create!(area: constantinople, neighbor: bulgaria_ec)
    Neighbor.create!(area: constantinople, neighbor: black_sea)
    Neighbor.create!(area: constantinople, neighbor: ankara)
    Neighbor.create!(area: constantinople, neighbor: smyrna)
    Neighbor.create!(area: constantinople, neighbor: aegean_sea)

    Neighbor.create!(area: denmark, neighbor: skagerrack)
    Neighbor.create!(area: denmark, neighbor: sweden)
    Neighbor.create!(area: denmark, neighbor: baltic_sea)
    Neighbor.create!(area: denmark, neighbor: kiel)
    Neighbor.create!(area: denmark, neighbor: heligoland_bight)
    Neighbor.create!(area: denmark, neighbor: north_sea)

    Neighbor.create!(area: edinburgh, neighbor: norwegian_sea)
    Neighbor.create!(area: edinburgh, neighbor: north_sea)
    Neighbor.create!(area: edinburgh, neighbor: yorkshire)
    Neighbor.create!(area: edinburgh, neighbor: liverpool)
    Neighbor.create!(area: edinburgh, neighbor: clyde)

    Neighbor.create!(area: greece, neighbor: albania)
    Neighbor.create!(area: greece, neighbor: serbia)
    Neighbor.create!(area: greece, neighbor: bulgaria_sc)
    Neighbor.create!(area: greece, neighbor: bulgaria)
    Neighbor.create!(area: greece, neighbor: aegean_sea)
    Neighbor.create!(area: greece, neighbor: ionian_sea)

    Neighbor.create!(area: holland, neighbor: heligoland_bight)
    Neighbor.create!(area: holland, neighbor: kiel)
    Neighbor.create!(area: holland, neighbor: ruhr)
    Neighbor.create!(area: holland, neighbor: belgium)
    Neighbor.create!(area: holland, neighbor: north_sea)

    Neighbor.create!(area: kiel, neighbor: denmark)
    Neighbor.create!(area: kiel, neighbor: baltic_sea)
    Neighbor.create!(area: kiel, neighbor: berlin)
    Neighbor.create!(area: kiel, neighbor: munich)
    Neighbor.create!(area: kiel, neighbor: ruhr)
    Neighbor.create!(area: kiel, neighbor: holland)
    Neighbor.create!(area: kiel, neighbor: heligoland_bight)

    Neighbor.create!(area: liverpool, neighbor: clyde)
    Neighbor.create!(area: liverpool, neighbor: edinburgh)
    Neighbor.create!(area: liverpool, neighbor: yorkshire)
    Neighbor.create!(area: liverpool, neighbor: wales)
    Neighbor.create!(area: liverpool, neighbor: irish_sea)
    Neighbor.create!(area: liverpool, neighbor: north_atlantic_ocean)

    Neighbor.create!(area: london, neighbor: yorkshire)
    Neighbor.create!(area: london, neighbor: north_sea)
    Neighbor.create!(area: london, neighbor: english_channel)
    Neighbor.create!(area: london, neighbor: wales)

    Neighbor.create!(area: marseilles, neighbor: spain_sc)
    Neighbor.create!(area: marseilles, neighbor: spain)
    Neighbor.create!(area: marseilles, neighbor: gascony)
    Neighbor.create!(area: marseilles, neighbor: burgundy)
    Neighbor.create!(area: marseilles, neighbor: piedmont)
    Neighbor.create!(area: marseilles, neighbor: gulf_of_lyons)

    Neighbor.create!(area: moscow, neighbor: saint_petersburg)
    Neighbor.create!(area: moscow, neighbor: sevastopol)
    Neighbor.create!(area: moscow, neighbor: ukraine)
    Neighbor.create!(area: moscow, neighbor: warsaw)
    Neighbor.create!(area: moscow, neighbor: livonia)

    Neighbor.create!(area: munich, neighbor: ruhr)
    Neighbor.create!(area: munich, neighbor: kiel)
    Neighbor.create!(area: munich, neighbor: berlin)
    Neighbor.create!(area: munich, neighbor: silesia)
    Neighbor.create!(area: munich, neighbor: bohemia)
    Neighbor.create!(area: munich, neighbor: tyrolia)
    Neighbor.create!(area: munich, neighbor: burgundy)

    Neighbor.create!(area: naples, neighbor: rome)
    Neighbor.create!(area: naples, neighbor: apulia)
    Neighbor.create!(area: naples, neighbor: ionian_sea)
    Neighbor.create!(area: naples, neighbor: tyrrhenian_sea)

    Neighbor.create!(area: norway, neighbor: saint_petersburg_nc)
    Neighbor.create!(area: norway, neighbor: saint_petersburg)
    Neighbor.create!(area: norway, neighbor: finland)
    Neighbor.create!(area: norway, neighbor: sweden)
    Neighbor.create!(area: norway, neighbor: skagerrack)
    Neighbor.create!(area: norway, neighbor: north_sea)
    Neighbor.create!(area: norway, neighbor: norwegian_sea)
    Neighbor.create!(area: norway, neighbor: barents_sea)

    Neighbor.create!(area: paris, neighbor: picardy)
    Neighbor.create!(area: paris, neighbor: burgundy)
    Neighbor.create!(area: paris, neighbor: gascony)
    Neighbor.create!(area: paris, neighbor: brest)

    Neighbor.create!(area: portugal, neighbor: mid_atlantic_ocean)
    Neighbor.create!(area: portugal, neighbor: spain_nc)
    Neighbor.create!(area: portugal, neighbor: spain)
    Neighbor.create!(area: portugal, neighbor: spain_sc)

    Neighbor.create!(area: rome, neighbor: tuscany)
    Neighbor.create!(area: rome, neighbor: venice)
    Neighbor.create!(area: rome, neighbor: apulia)
    Neighbor.create!(area: rome, neighbor: naples)
    Neighbor.create!(area: rome, neighbor: tyrrhenian_sea)

    Neighbor.create!(area: rumania, neighbor: budapest)
    Neighbor.create!(area: rumania, neighbor: galicia)
    Neighbor.create!(area: rumania, neighbor: ukraine)
    Neighbor.create!(area: rumania, neighbor: sevastopol)
    Neighbor.create!(area: rumania, neighbor: black_sea)
    Neighbor.create!(area: rumania, neighbor: bulgaria_ec)
    Neighbor.create!(area: rumania, neighbor: bulgaria)
    Neighbor.create!(area: rumania, neighbor: serbia)

    Neighbor.create!(area: saint_petersburg, neighbor: moscow)
    Neighbor.create!(area: saint_petersburg, neighbor: livonia)
    Neighbor.create!(area: saint_petersburg, neighbor: gulf_of_bothnia)
    Neighbor.create!(area: saint_petersburg, neighbor: finland)
    Neighbor.create!(area: saint_petersburg, neighbor: norway)
    Neighbor.create!(area: saint_petersburg, neighbor: barents_sea)

    Neighbor.create!(area: serbia, neighbor: trieste)
    Neighbor.create!(area: serbia, neighbor: budapest)
    Neighbor.create!(area: serbia, neighbor: rumania)
    Neighbor.create!(area: serbia, neighbor: bulgaria)
    Neighbor.create!(area: serbia, neighbor: greece)
    Neighbor.create!(area: serbia, neighbor: albania)

    Neighbor.create!(area: sevastopol, neighbor: ukraine)
    Neighbor.create!(area: sevastopol, neighbor: moscow)
    Neighbor.create!(area: sevastopol, neighbor: armenia)
    Neighbor.create!(area: sevastopol, neighbor: black_sea)
    Neighbor.create!(area: sevastopol, neighbor: rumania)

    Neighbor.create!(area: smyrna, neighbor: constantinople)
    Neighbor.create!(area: smyrna, neighbor: ankara)
    Neighbor.create!(area: smyrna, neighbor: armenia)
    Neighbor.create!(area: smyrna, neighbor: syria)
    Neighbor.create!(area: smyrna, neighbor: eastern_mediterranean)
    Neighbor.create!(area: smyrna, neighbor: aegean_sea)

    Neighbor.create!(area: spain, neighbor: gascony)
    Neighbor.create!(area: spain, neighbor: marseilles)
    Neighbor.create!(area: spain, neighbor: gulf_of_lyons)
    Neighbor.create!(area: spain, neighbor: western_mediterranean)
    Neighbor.create!(area: spain, neighbor: portugal)
    Neighbor.create!(area: spain, neighbor: mid_atlantic_ocean)

    Neighbor.create!(area: sweden, neighbor: norway)
    Neighbor.create!(area: sweden, neighbor: finland)
    Neighbor.create!(area: sweden, neighbor: gulf_of_bothnia)
    Neighbor.create!(area: sweden, neighbor: baltic_sea)
    Neighbor.create!(area: sweden, neighbor: denmark)
    Neighbor.create!(area: sweden, neighbor: skagerrack)

    Neighbor.create!(area: trieste, neighbor: venice)
    Neighbor.create!(area: trieste, neighbor: tyrolia)
    Neighbor.create!(area: trieste, neighbor: vienna)
    Neighbor.create!(area: trieste, neighbor: budapest)
    Neighbor.create!(area: trieste, neighbor: serbia)
    Neighbor.create!(area: trieste, neighbor: albania)
    Neighbor.create!(area: trieste, neighbor: adriatic_sea)

    Neighbor.create!(area: tunis, neighbor: north_africa)
    Neighbor.create!(area: tunis, neighbor: western_mediterranean)
    Neighbor.create!(area: tunis, neighbor: tyrrhenian_sea)
    Neighbor.create!(area: tunis, neighbor: ionian_sea)

    Neighbor.create!(area: venice, neighbor: apulia)
    Neighbor.create!(area: venice, neighbor: rome)
    Neighbor.create!(area: venice, neighbor: tuscany)
    Neighbor.create!(area: venice, neighbor: piedmont)
    Neighbor.create!(area: venice, neighbor: tyrolia)
    Neighbor.create!(area: venice, neighbor: trieste)
    Neighbor.create!(area: venice, neighbor: adriatic_sea)

    Neighbor.create!(area: vienna, neighbor: tyrolia)
    Neighbor.create!(area: vienna, neighbor: bohemia)
    Neighbor.create!(area: vienna, neighbor: galicia)
    Neighbor.create!(area: vienna, neighbor: budapest)
    Neighbor.create!(area: vienna, neighbor: trieste)

    Neighbor.create!(area: warsaw, neighbor: silesia)
    Neighbor.create!(area: warsaw, neighbor: prussia)
    Neighbor.create!(area: warsaw, neighbor: livonia)
    Neighbor.create!(area: warsaw, neighbor: moscow)
    Neighbor.create!(area: warsaw, neighbor: ukraine)
    Neighbor.create!(area: warsaw, neighbor: galicia)

    Neighbor.create!(area: clyde, neighbor: edinburgh)
    Neighbor.create!(area: clyde, neighbor: liverpool)
    Neighbor.create!(area: clyde, neighbor: north_atlantic_ocean)
    Neighbor.create!(area: clyde, neighbor: norwegian_sea)

    Neighbor.create!(area: yorkshire, neighbor: london)
    Neighbor.create!(area: yorkshire, neighbor: wales)
    Neighbor.create!(area: yorkshire, neighbor: liverpool)
    Neighbor.create!(area: yorkshire, neighbor: edinburgh)
    Neighbor.create!(area: yorkshire, neighbor: north_sea)

    Neighbor.create!(area: wales, neighbor: liverpool)
    Neighbor.create!(area: wales, neighbor: yorkshire)
    Neighbor.create!(area: wales, neighbor: london)
    Neighbor.create!(area: wales, neighbor: english_channel)
    Neighbor.create!(area: wales, neighbor: irish_sea)

    Neighbor.create!(area: picardy, neighbor: belgium)
    Neighbor.create!(area: picardy, neighbor: burgundy)
    Neighbor.create!(area: picardy, neighbor: paris)
    Neighbor.create!(area: picardy, neighbor: brest)
    Neighbor.create!(area: picardy, neighbor: english_channel)

    Neighbor.create!(area: gascony, neighbor: brest)
    Neighbor.create!(area: gascony, neighbor: paris)
    Neighbor.create!(area: gascony, neighbor: burgundy)
    Neighbor.create!(area: gascony, neighbor: marseilles)
    Neighbor.create!(area: gascony, neighbor: spain)
    Neighbor.create!(area: gascony, neighbor: spain_nc)
    Neighbor.create!(area: gascony, neighbor: mid_atlantic_ocean)

    Neighbor.create!(area: burgundy, neighbor: belgium)
    Neighbor.create!(area: burgundy, neighbor: ruhr)
    Neighbor.create!(area: burgundy, neighbor: munich)
    Neighbor.create!(area: burgundy, neighbor: marseilles)
    Neighbor.create!(area: burgundy, neighbor: gascony)
    Neighbor.create!(area: burgundy, neighbor: paris)
    Neighbor.create!(area: burgundy, neighbor: picardy)

    Neighbor.create!(area: north_africa, neighbor: mid_atlantic_ocean)
    Neighbor.create!(area: north_africa, neighbor: western_mediterranean)
    Neighbor.create!(area: north_africa, neighbor: tunis)

    Neighbor.create!(area: ruhr, neighbor: belgium)
    Neighbor.create!(area: ruhr, neighbor: holland)
    Neighbor.create!(area: ruhr, neighbor: kiel)
    Neighbor.create!(area: ruhr, neighbor: munich)
    Neighbor.create!(area: ruhr, neighbor: burgundy)

    Neighbor.create!(area: prussia, neighbor: livonia)
    Neighbor.create!(area: prussia, neighbor: warsaw)
    Neighbor.create!(area: prussia, neighbor: silesia)
    Neighbor.create!(area: prussia, neighbor: berlin)
    Neighbor.create!(area: prussia, neighbor: baltic_sea)

    Neighbor.create!(area: silesia, neighbor: munich)
    Neighbor.create!(area: silesia, neighbor: berlin)
    Neighbor.create!(area: silesia, neighbor: prussia)
    Neighbor.create!(area: silesia, neighbor: warsaw)
    Neighbor.create!(area: silesia, neighbor: galicia)
    Neighbor.create!(area: silesia, neighbor: bohemia)

    Neighbor.create!(area: piedmont, neighbor: marseilles)
    Neighbor.create!(area: piedmont, neighbor: tyrolia)
    Neighbor.create!(area: piedmont, neighbor: venice)
    Neighbor.create!(area: piedmont, neighbor: tuscany)
    Neighbor.create!(area: piedmont, neighbor: gulf_of_lyons)

    Neighbor.create!(area: tuscany, neighbor: piedmont)
    Neighbor.create!(area: tuscany, neighbor: venice)
    Neighbor.create!(area: tuscany, neighbor: rome)
    Neighbor.create!(area: tuscany, neighbor: tyrrhenian_sea)
    Neighbor.create!(area: tuscany, neighbor: gulf_of_lyons)

    Neighbor.create!(area: apulia, neighbor: naples)
    Neighbor.create!(area: apulia, neighbor: rome)
    Neighbor.create!(area: apulia, neighbor: venice)
    Neighbor.create!(area: apulia, neighbor: adriatic_sea)
    Neighbor.create!(area: apulia, neighbor: ionian_sea)

    Neighbor.create!(area: tyrolia, neighbor: munich)
    Neighbor.create!(area: tyrolia, neighbor: bohemia)
    Neighbor.create!(area: tyrolia, neighbor: vienna)
    Neighbor.create!(area: tyrolia, neighbor: trieste)
    Neighbor.create!(area: tyrolia, neighbor: venice)
    Neighbor.create!(area: tyrolia, neighbor: piedmont)

    Neighbor.create!(area: galicia, neighbor: warsaw)
    Neighbor.create!(area: galicia, neighbor: ukraine)
    Neighbor.create!(area: galicia, neighbor: rumania)
    Neighbor.create!(area: galicia, neighbor: budapest)
    Neighbor.create!(area: galicia, neighbor: vienna)
    Neighbor.create!(area: galicia, neighbor: bohemia)
    Neighbor.create!(area: galicia, neighbor: silesia)

    Neighbor.create!(area: bohemia, neighbor: munich)
    Neighbor.create!(area: bohemia, neighbor: silesia)
    Neighbor.create!(area: bohemia, neighbor: galicia)
    Neighbor.create!(area: bohemia, neighbor: vienna)
    Neighbor.create!(area: bohemia, neighbor: tyrolia)

    Neighbor.create!(area: finland, neighbor: sweden)
    Neighbor.create!(area: finland, neighbor: norway)
    Neighbor.create!(area: finland, neighbor: saint_petersburg)
    Neighbor.create!(area: finland, neighbor: saint_petersburg_sc)
    Neighbor.create!(area: finland, neighbor: gulf_of_bothnia)

    Neighbor.create!(area: livonia, neighbor: saint_petersburg_sc)
    Neighbor.create!(area: livonia, neighbor: saint_petersburg)
    Neighbor.create!(area: livonia, neighbor: moscow)
    Neighbor.create!(area: livonia, neighbor: warsaw)
    Neighbor.create!(area: livonia, neighbor: prussia)
    Neighbor.create!(area: livonia, neighbor: baltic_sea)
    Neighbor.create!(area: livonia, neighbor: gulf_of_bothnia)

    Neighbor.create!(area: ukraine, neighbor: warsaw)
    Neighbor.create!(area: ukraine, neighbor: moscow)
    Neighbor.create!(area: ukraine, neighbor: sevastopol)
    Neighbor.create!(area: ukraine, neighbor: rumania)
    Neighbor.create!(area: ukraine, neighbor: galicia)

    Neighbor.create!(area: albania, neighbor: trieste)
    Neighbor.create!(area: albania, neighbor: serbia)
    Neighbor.create!(area: albania, neighbor: greece)
    Neighbor.create!(area: albania, neighbor: ionian_sea)
    Neighbor.create!(area: albania, neighbor: adriatic_sea)

    Neighbor.create!(area: armenia, neighbor: sevastopol)
    Neighbor.create!(area: armenia, neighbor: syria)
    Neighbor.create!(area: armenia, neighbor: smyrna)
    Neighbor.create!(area: armenia, neighbor: ankara)
    Neighbor.create!(area: armenia, neighbor: black_sea)

    Neighbor.create!(area: syria, neighbor: smyrna)
    Neighbor.create!(area: syria, neighbor: armenia)
    Neighbor.create!(area: syria, neighbor: eastern_mediterranean)

    Neighbor.create!(area: north_atlantic_ocean, neighbor: norwegian_sea)
    Neighbor.create!(area: north_atlantic_ocean, neighbor: clyde)
    Neighbor.create!(area: north_atlantic_ocean, neighbor: liverpool)
    Neighbor.create!(area: north_atlantic_ocean, neighbor: irish_sea)
    Neighbor.create!(area: north_atlantic_ocean, neighbor: mid_atlantic_ocean)

    Neighbor.create!(area: mid_atlantic_ocean, neighbor: north_atlantic_ocean)
    Neighbor.create!(area: mid_atlantic_ocean, neighbor: irish_sea)
    Neighbor.create!(area: mid_atlantic_ocean, neighbor: english_channel)
    Neighbor.create!(area: mid_atlantic_ocean, neighbor: brest)
    Neighbor.create!(area: mid_atlantic_ocean, neighbor: gascony)
    Neighbor.create!(area: mid_atlantic_ocean, neighbor: spain_nc)
    Neighbor.create!(area: mid_atlantic_ocean, neighbor: spain)
    Neighbor.create!(area: mid_atlantic_ocean, neighbor: spain_sc)
    Neighbor.create!(area: mid_atlantic_ocean, neighbor: portugal)
    Neighbor.create!(area: mid_atlantic_ocean, neighbor: north_africa)

    Neighbor.create!(area: norwegian_sea, neighbor: north_atlantic_ocean)
    Neighbor.create!(area: norwegian_sea, neighbor: barents_sea)
    Neighbor.create!(area: norwegian_sea, neighbor: norway)
    Neighbor.create!(area: norwegian_sea, neighbor: north_sea)
    Neighbor.create!(area: norwegian_sea, neighbor: edinburgh)
    Neighbor.create!(area: norwegian_sea, neighbor: clyde)

    Neighbor.create!(area: north_sea, neighbor: norwegian_sea)
    Neighbor.create!(area: north_sea, neighbor: norway)
    Neighbor.create!(area: north_sea, neighbor: skagerrack)
    Neighbor.create!(area: north_sea, neighbor: denmark)
    Neighbor.create!(area: north_sea, neighbor: heligoland_bight)
    Neighbor.create!(area: north_sea, neighbor: holland)
    Neighbor.create!(area: north_sea, neighbor: belgium)
    Neighbor.create!(area: north_sea, neighbor: english_channel)
    Neighbor.create!(area: north_sea, neighbor: london)
    Neighbor.create!(area: north_sea, neighbor: yorkshire)
    Neighbor.create!(area: north_sea, neighbor: edinburgh)

    Neighbor.create!(area: english_channel, neighbor: mid_atlantic_ocean)
    Neighbor.create!(area: english_channel, neighbor: irish_sea)
    Neighbor.create!(area: english_channel, neighbor: wales)
    Neighbor.create!(area: english_channel, neighbor: london)
    Neighbor.create!(area: english_channel, neighbor: north_sea)
    Neighbor.create!(area: english_channel, neighbor: belgium)
    Neighbor.create!(area: english_channel, neighbor: picardy)
    Neighbor.create!(area: english_channel, neighbor: brest)

    Neighbor.create!(area: irish_sea, neighbor: liverpool)
    Neighbor.create!(area: irish_sea, neighbor: wales)
    Neighbor.create!(area: irish_sea, neighbor: english_channel)
    Neighbor.create!(area: irish_sea, neighbor: mid_atlantic_ocean)
    Neighbor.create!(area: irish_sea, neighbor: north_atlantic_ocean)

    Neighbor.create!(area: heligoland_bight, neighbor: north_sea)
    Neighbor.create!(area: heligoland_bight, neighbor: denmark)
    Neighbor.create!(area: heligoland_bight, neighbor: kiel)
    Neighbor.create!(area: heligoland_bight, neighbor: holland)

    Neighbor.create!(area: skagerrack, neighbor: north_sea)
    Neighbor.create!(area: skagerrack, neighbor: norway)
    Neighbor.create!(area: skagerrack, neighbor: sweden)
    Neighbor.create!(area: skagerrack, neighbor: denmark)

    Neighbor.create!(area: baltic_sea, neighbor: denmark)
    Neighbor.create!(area: baltic_sea, neighbor: sweden)
    Neighbor.create!(area: baltic_sea, neighbor: gulf_of_bothnia)
    Neighbor.create!(area: baltic_sea, neighbor: livonia)
    Neighbor.create!(area: baltic_sea, neighbor: prussia)
    Neighbor.create!(area: baltic_sea, neighbor: berlin)
    Neighbor.create!(area: baltic_sea, neighbor: kiel)

    Neighbor.create!(area: gulf_of_bothnia, neighbor: sweden)
    Neighbor.create!(area: gulf_of_bothnia, neighbor: finland)
    Neighbor.create!(area: gulf_of_bothnia, neighbor: saint_petersburg)
    Neighbor.create!(area: gulf_of_bothnia, neighbor: saint_petersburg_sc)
    Neighbor.create!(area: gulf_of_bothnia, neighbor: livonia)
    Neighbor.create!(area: gulf_of_bothnia, neighbor: baltic_sea)

    Neighbor.create!(area: barents_sea, neighbor: saint_petersburg)
    Neighbor.create!(area: barents_sea, neighbor: saint_petersburg_nc)
    Neighbor.create!(area: barents_sea, neighbor: norway)
    Neighbor.create!(area: barents_sea, neighbor: norwegian_sea)

    Neighbor.create!(area: western_mediterranean, neighbor: spain)
    Neighbor.create!(area: western_mediterranean, neighbor: spain_sc)
    Neighbor.create!(area: western_mediterranean, neighbor: gulf_of_lyons)
    Neighbor.create!(area: western_mediterranean, neighbor: tyrrhenian_sea)
    Neighbor.create!(area: western_mediterranean, neighbor: tunis)
    Neighbor.create!(area: western_mediterranean, neighbor: north_africa)
    Neighbor.create!(area: western_mediterranean, neighbor: mid_atlantic_ocean)

    Neighbor.create!(area: gulf_of_lyons, neighbor: spain)
    Neighbor.create!(area: gulf_of_lyons, neighbor: spain_sc)
    Neighbor.create!(area: gulf_of_lyons, neighbor: marseilles)
    Neighbor.create!(area: gulf_of_lyons, neighbor: piedmont)
    Neighbor.create!(area: gulf_of_lyons, neighbor: tuscany)
    Neighbor.create!(area: gulf_of_lyons, neighbor: tyrrhenian_sea)
    Neighbor.create!(area: gulf_of_lyons, neighbor: western_mediterranean)

    Neighbor.create!(area: tyrrhenian_sea, neighbor: western_mediterranean)
    Neighbor.create!(area: tyrrhenian_sea, neighbor: gulf_of_lyons)
    Neighbor.create!(area: tyrrhenian_sea, neighbor: tuscany)
    Neighbor.create!(area: tyrrhenian_sea, neighbor: rome)
    Neighbor.create!(area: tyrrhenian_sea, neighbor: naples)
    Neighbor.create!(area: tyrrhenian_sea, neighbor: ionian_sea)
    Neighbor.create!(area: tyrrhenian_sea, neighbor: tunis)

    Neighbor.create!(area: ionian_sea, neighbor: tyrrhenian_sea)
    Neighbor.create!(area: ionian_sea, neighbor: naples)
    Neighbor.create!(area: ionian_sea, neighbor: apulia)
    Neighbor.create!(area: ionian_sea, neighbor: adriatic_sea)
    Neighbor.create!(area: ionian_sea, neighbor: albania)
    Neighbor.create!(area: ionian_sea, neighbor: greece)
    Neighbor.create!(area: ionian_sea, neighbor: aegean_sea)
    Neighbor.create!(area: ionian_sea, neighbor: eastern_mediterranean)
    Neighbor.create!(area: ionian_sea, neighbor: tunis)

    Neighbor.create!(area: adriatic_sea, neighbor: trieste)
    Neighbor.create!(area: adriatic_sea, neighbor: albania)
    Neighbor.create!(area: adriatic_sea, neighbor: ionian_sea)
    Neighbor.create!(area: adriatic_sea, neighbor: apulia)
    Neighbor.create!(area: adriatic_sea, neighbor: venice)

    Neighbor.create!(area: aegean_sea, neighbor: greece)
    Neighbor.create!(area: aegean_sea, neighbor: bulgaria_sc)
    Neighbor.create!(area: aegean_sea, neighbor: bulgaria)
    Neighbor.create!(area: aegean_sea, neighbor: constantinople)
    Neighbor.create!(area: aegean_sea, neighbor: smyrna)
    Neighbor.create!(area: aegean_sea, neighbor: eastern_mediterranean)
    Neighbor.create!(area: aegean_sea, neighbor: ionian_sea)

    Neighbor.create!(area: eastern_mediterranean, neighbor: smyrna)
    Neighbor.create!(area: eastern_mediterranean, neighbor: syria)
    Neighbor.create!(area: eastern_mediterranean, neighbor: ionian_sea)
    Neighbor.create!(area: eastern_mediterranean, neighbor: aegean_sea)

    Neighbor.create!(area: black_sea, neighbor: sevastopol)
    Neighbor.create!(area: black_sea, neighbor: armenia)
    Neighbor.create!(area: black_sea, neighbor: ankara)
    Neighbor.create!(area: black_sea, neighbor: constantinople)
    Neighbor.create!(area: black_sea, neighbor: bulgaria)
    Neighbor.create!(area: black_sea, neighbor: bulgaria_ec)
    Neighbor.create!(area: black_sea, neighbor: rumania)
  end

  def self.teardown
    Neighbor.destroy_all
    Coast.destroy_all
    Area.destroy_all
  end
end
